# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0.2'

target 'Visualize_Data' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Visualize_Data
	# Add the Firebase pod for Google Analytics
	pod 'FirebaseAnalytics'
	pod 'Firebase/Core'

	# For Analytics without IDFA collection capability, use this pod instead
	# pod ‘Firebase/AnalyticsWithoutAdIdSupport’

	# Add the pods for any other Firebase products you want to use in your app
	# For example, to use Firebase Authentication and Cloud Firestore
	pod 'FirebaseAuth'
	pod 'FirebaseFirestore'

  target 'Visualize_DataTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Visualize_DataUITests' do
    # Pods for testing
  end

end
